# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztFSIxsgQsK0z0Q9nwetUg5RzxiVLvwD
"""

import pandas as pd
import streamlit as st
import plotly.express as px

# =======================
# CONFIGURAÇÃO INICIAL
# =======================
st.set_page_config(layout="wide", page_title="GeoAgro - Dashboard Interativo", page_icon="🌾")

# =======================
# LEITURA DOS DADOS
# =======================
df = pd.read_csv("dados.csv")

colunas_novas = {
    'Safra': 'safra',
    'Regiao': 'regiao',
    'Municipio': 'municipio',
    'Latitude': 'latitude',
    'Longitude': 'longitude',
    'Altitude': 'altitude',
    'Rendimento (Kg/ha)': 'rendimento_kg_ha',
    'Reduçao-chuvas (%)': 'reducao_chuvas_perc',
    'Queda Rendimento 18-19': 'queda_rendimento_perc'
}
df.rename(columns=colunas_novas, inplace=True)

def classificar_regiao(latitude):
    if latitude >= -24:
        return 'Norte_Parana'
    elif latitude < -24 and latitude >= -25.5:
        return 'Centro_Parana'
    else:
        return 'Sul_Parana'

df['regiao_geo'] = df['latitude'].apply(classificar_regiao)

# =======================
# LAYOUT E FILTROS
# =======================
st.title("🌾 GeoAgro Dashboard - Análise de Risco Climático da Soja no Paraná")

st.sidebar.header("🎯 Filtros de Visualização")
regioes = sorted(df['regiao_geo'].unique())
regiao_selecionada = st.sidebar.selectbox("Selecione uma Região:", regioes)

df_filtrado = df[df['regiao_geo'] == regiao_selecionada]

st.markdown(f"### Região Selecionada: **{regiao_selecionada}**")

# =======================
# MAPA INTERATIVO
# =======================
fig = px.scatter_mapbox(
    df_filtrado,
    lat='latitude',
    lon='longitude',
    color='queda_rendimento_perc',
    size='rendimento_kg_ha',
    hover_name='municipio',
    hover_data={
        'rendimento_kg_ha': ':.2f} kg/ha',
        'queda_rendimento_perc': ':.2f}%',
        'reducao_chuvas_perc': ':.2f}%'
    },
    color_continuous_scale=px.colors.sequential.Reds,
    zoom=6,
    height=600
)
fig.update_layout(mapbox_style='open-street-map', margin={'r':0,'t':0,'l':0,'b':0})
st.plotly_chart(fig, use_container_width=True)

# =======================
# TABELA RESUMIDA
# =======================
st.markdown("#### 📊 Ranking dos Municípios - Queda de Rendimento (%)")
tabela_resumo = df_filtrado[['municipio', 'rendimento_kg_ha', 'queda_rendimento_perc']].sort_values('queda_rendimento_perc', ascending=False)
st.dataframe(tabela_resumo, use_container_width=True)

# =======================
# CORRELAÇÃO RÁPIDA
# =======================
st.markdown("#### 🔍 Correlação entre Redução de Chuvas e Queda de Rendimento")
correlacao = df_filtrado[['reducao_chuvas_perc', 'queda_rendimento_perc']].corr().iloc[0,1]
st.metric("Correlação (ρ)", f"{correlacao:.2f}")
