# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztFSIxsgQsK0z0Q9nwetUg5RzxiVLvwD
"""

import pandas as pd
import streamlit as st
import plotly.express as px

# =======================
# CONFIGURAÇÃO INICIAL
# =======================
st.set_page_config(layout="wide", page_title="GeoAgro - Risco Soja PR", page_icon="🗺️")

# =======================
# LEITURA DOS DADOS
# =======================
df = pd.read_csv("dados.csv")

# Padroniza nomes de colunas
colunas_novas = {
    'Safra': 'safra',
    'Regiao': 'regiao',
    'Municipio': 'municipio',
    'Latitude': 'latitude',
    'Longitude': 'longitude',
    'Altitude': 'altitude',
    'Rendimento (Kg/ha)': 'rendimento_kg_ha',
    'Reduçao-chuvas (%)': 'reducao_chuvas_perc',
    'Queda Rendimento 18-19': 'queda_rendimento_perc'
}
df.rename(columns=colunas_novas, inplace=True)

# =======================
# CLASSIFICAÇÃO GEOGRÁFICA
# =======================
def classificar_regiao(latitude):
    if latitude >= -24:
        return 'Norte_Parana'
    elif latitude < -24 and latitude >= -25.5:
        return 'Centro_Parana'
    else:
        return 'Sul_Parana'

df['regiao_geo'] = df['latitude'].apply(classificar_regiao)

# =======================
# TÍTULO E MAPA INTERATIVO
# =======================
st.markdown("## 🗺️ Mapa Interativo: Queda de Rendimento da Soja no Paraná")

fig = px.scatter_mapbox(
    df,
    lat='latitude',
    lon='longitude',
    color='queda_rendimento_perc',
    size='rendimento_kg_ha',
    hover_name='municipio',
    hover_data={
        'rendimento_kg_ha': ':.2f} kg/ha',
        'queda_rendimento_perc': ':.2f}%',
        'reducao_chuvas_perc': ':.2f}%'
    },
    color_continuous_scale=px.colors.sequential.Reds,
    zoom=6.5,
    height=750
)
fig.update_layout(mapbox_style='open-street-map', margin={'r':0, 't':0, 'l':0, 'b':0})

st.plotly_chart(fig, use_container_width=True)


